apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: client-to-web
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ubuntuapp-ohoh
