apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: client-to-web
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.32.0.0/12
        except:
        - 10.47.255.0/24
    - podSelector:
        matchLabels:
          app: ubuntuapp
    ports:
    - protocol: TCP
      port: 80
