apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
 name: contrail-policy
 namespace: policy-namespace
spec:
 podSelector:
  matchLabels:
    app: frontend
 egress:
  - ports:
    - port: 80
      protocol: TCP
 ingress:
  - from:
     - podSelector:
        matchLabels:
         app: ubuntuapp
