apiVersion: v1
kind: Pod
metadata:
 name: mysniffer
 annotations:
   "opencontrail.org/network" : '{"domain":"default-domain", "project": "admin", "name": "myMirroring"}'
 labels:
   app: ubuntuapp
spec:
 containers:
   - name: ubuntuap
     image: virtualhops/ato-ubuntu:latest
     ports:
     - containerPort: 80
