apiVersion: v1
kind: Pod
metadata:
 name: ubuntuapp
 #annotations:
 #  "opencontrail.org/network" : '{"domain":"default-domain", "project": "admin", "name": "custom-vn"}'
 labels:
   app: ubuntuapp
spec:
 containers:
   - name: ubuntuapp
     image: virtualhops/ato-ubuntu:latest
     ports:
     - containerPort: 80
