apiVersion: v1
kind: Pod
metadata:
 name: ubuntuapp-custom
 annotations:
   "opencontrail.org/network" : '{"domain":"default-domain", "project": "default", "name": "net1"}'
 labels:
   app: ubuntuapp
spec:
 containers:
   - name: ubuntuapp
     image: virtualhops/ato-ubuntu:latest
     ports:
     - containerPort: 80
