apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-dev
spec:
  replicas: 3
  selector:
    app: frontend
  template:
    metadata:
      name: frontend-dev
      labels:
        app: frontend
        role: dev
    spec:
      containers:
      - name: web-app-dev
        image: savvythru/web-app-dev
        ports:
        - containerPort: 80
