apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-qa
spec:
  replicas: 3
  selector:
    app: frontend
  template:
    metadata:
      name: frontend-qa
      labels:
        app: frontend
        role: qa
    spec:
      containers:
      - name: web-app-qa
        image: savvythru/web-app-qa
        ports:
        - containerPort: 80
